### PR TITLE
Release 3.5.0, support py313

### PR DESCRIPTION
**Pull request by bobleesj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bobleesj** [comment]
@conda-forge-admin, please rerender

**Comment by bobleesj** [comment]
@sbillinge very odd that linux CI isn't running - not ready to be merged.

**Comment by bobleesj** [comment]
@conda-forge-admin, please rerender

let's re-render to see whether CI can appear.

**Comment by bobleesj** [comment]
@conda-forge-admin @xhochy

It appears that no Linux CI is currently appearing in this PR, even though we have seen it in other feedstocks that follow the same `meta.yaml` format. Please see this link: https://github.com/conda-forge/diffpy.srmise-feedstock/pull/5.

Could you please provide guidance on how to run the Linux build CI again?

**Comment by bobleesj** [comment]
@conda-forge-admin, please rerender

**Comment by bobleesj** [comment]
@ocefpaf Could you please provide insight into why Linux CI isn't automatically running for this PR? We're also noticing Linux CI not executing in three other feedstocks as well.

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/status/issues/188

**Comment by bobleesj** [comment]
@conda-forge-admin, please rerender

**Comment by bobleesj** [comment]
@ocefpaf Thanks! seems like CI is running again. Appreciate your support as always.

**Comment by bobleesj** [comment]
@sbillinge ready to be merged - will release pdfmoprh as well after testing diffpy.utils py313 support.

**Comment by sbillinge** [comment]
@bobleesj thanks, done.  Do I have to also redo diffpy.structure?

**Comment by bobleesj** [comment]
yes, will make a comment in diffpy.structure-feedstock

**Pull request merged**
