### PR TITLE
diffpy.utils 3.2.1

### PR DESCRIPTION
**Pull request by sbillinge**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by sbillinge** [comment]
@conda-forge-admin, please rerender

**Comment by sbillinge** [comment]
@pavoljuhas @dragonyanglong @CJ-Wright please could you grant write access to @sbillinge (Simon) and @Sparks29032 (Andrew, student) so we can become maintainers?  Thanks very much.

**Comment by pavoljuhas** [comment]
> @pavoljuhas @dragonyanglong @CJ-Wright please could you grant write access to @sbillinge (Simon) and @Sparks29032 (Andrew, student) so we can become maintainers? Thanks very much.

Done.  Note I reverted version bump which will need to be done in a new PR.

**Comment by sbillinge** [comment]
Thanks Pavol

**Pull request merged**
