### PR TITLE
Update to 3.4.1

### LINKED ISSUE #32: Remove jinja variable for SHA256 in meta.yaml
### Comment:

As recommended by https://github.com/conda-forge/staged-recipes/pull/27265/files#r1736210779

### PR DESCRIPTION
**Pull request by bobleesj**
Closes https://github.com/conda-forge/diffpy.utils-feedstock/issues/32

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Sparks29032** [comment]
Why did we remove the imports section?

**Comment by bobleesj** [comment]
> Why did we remove the imports section?

We are running full (py)tests so those imports are redundant. We also do not have `diffpy.utils.tests`  anymore since we separates `tests` from the `src` path.

**Comment by Sparks29032** [comment]
Got it!

**Comment by bobleesj** [comment]
@sbillinge diffpy.utils 3.4.1 ready for review. Pytest running here.

**Review by sbillinge — COMMENTED** [review]
Thanks @bobleesj for testing.  This looks good.  So if I understand, even without the `run_tests.py` it is running tests, is that correct?  

We will have to test after merging by creating a clean env and making sure the code runs fine to see if removing the `preserve_egg_dir` has any negative consequences (I hope not)

Just one last thing, I don't think it has  BSD-3 clause license, right?  It is fairly wide-open one but it is not BSD-3

**Comment by sbillinge** [comment]
I guess one more thing, do we need to pin it to numpy <2 or can we open this up?

**Comment by bobleesj** [comment]
> 1. Thanks @bobleesj for testing. This looks good. So if I understand, even without the run_tests.py it is running tests, is that correct?

Yes, we explicitly command Azure to run `pytest` that can be verified inside the CI logs. 

```
commands:
    - pip check
    - pytest
```

> 2. We will have to test after merging by creating a clean env and making sure the code runs fine to see if removing the preserve_egg_dir has any negative consequences (I hope not)

I will test the package after being merged. Since we are running full pytests here from the installed env, hopefully not.

> 3. I don't think it has BSD-3 clause license, right? It is fairly wide-open one but it is not BSD-3I 

I am currently seeing BSD-3 [LICENSE.rst](https://github.com/diffpy/diffpy.utils/blob/main/LICENSE.rst) in the latest repo. 

But, I checked our older repo (as of June 2024), I see two licenses:

https://github.com/diffpy/diffpy.utils/blob/8a861c01376f2164ac9f08239cbf960129a997f8/LICENSE.txt

and

https://github.com/diffpy/diffpy.utils/blob/8a861c01376f2164ac9f08239cbf960129a997f8/LICENSE_DANSE.txt

Could yo please advise?

> 4. I guess one more thing, do we need to pin it to numpy <2 or can we open this up?

```
The following NEW packages will be INSTALLED:

    ncurses:          6.5-he02047a_1             conda-forge
    numpy:            2.1.1-py312h58c1407_0      conda-forge
```

Based on the CI log, I am seeing `numpy 2.1.1 being installed and no warning is produced.

**Comment by bobleesj** [comment]
@sbillinge Seems like this PR was closed, due to the license?

**Comment by sbillinge** [comment]
> @sbillinge Seems like this PR was closed, due to the license?

yes, we don't want to merge this.

**Pull request closed without merging**
