### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@CJ-Wright - I am not sure this is needed, as the recipe is effectively the same.

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes What are good guidelines for bumping build number vs. not bumping build number?
I have seen examples where even just a change to the dev_url prompts for a build number increase: https://github.com/conda-forge/pyfai-feedstock/pull/12

**Comment by pavoljuhas** [comment]
> I have seen examples where even just a change to the dev_url prompts for a build number increase: conda-forge/pyfai-feedstock#12

That one seems to also adjust the [NumPy version used in the build](https://github.com/conda-forge/pyfai-feedstock/pull/12/files#diff-072cea419befcfca383c45968d4c00b5R118), and thus modify the "npXYZ" build tag on the produced package.

**Comment by mwcraig** [comment]
My reasoning here may be a bit circular, but since the recipe is part of the package, if the recipe changes then the package number should get bumped. 

In this particular feedstock, the change to the recipe that was pushed to master did *not* re-upload the packages, I think because the build number and version number matched what is already on anaconda.org, so no harm was done (see, e.g. https://travis-ci.org/conda-forge/diffpy.utils-feedstock/builds/247597938#L355).

If there are minor changes to a recipe and I think I'll remember to fix them later I just wait until there is a version update. 

The bigger issue is with pushing directly to master if the change in the recipe will trigger a new build (because either the version or the build number or both changed)...it is surprisingly easy [1] to introduce an error that would otherwise have been caught by CI.

The rule of thumb I use [2] is to always do a PR from a fork on my personal account.

As mentioned in the discussion thread you mentioned, it is a bit of a hassle to remove broken builds, so avoiding that is appreciated [3].

That said, just about any mistake that can be made has been made in the past [4] and can be fixed.

In this particular case I do not think you need to rebuild with a new build number since the original package is still on anaconda.org. The next time you make a change that actually does a new release the line ending change will be included. 

In the future it would be great if you did changes (even minor ones) by PR.

Translations:

[1]: I've broken packages many times this way, too many to track down a specific example. Probably I've even broken entire conda channels this way...

[2]: I'm not likely to remember complicated rules but can always manage to open a PR. 

[3]: Appreciated by the people who clean these things up...though I'm part of core I'm pretty far removed from the technical bits at this point.

[4]: By me, and presumably by others ;).

**Pull request closed without merging**
